DROP TABLE IF EXISTS AEROPUERTO;
CREATE TABLE AEROPUERTO(
	ID_AEROPUERTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CODIGO VARCHAR(10),
	NOMBRE VARCHAR(100),
	UBICACION VARCHAR(50),
	MTS_ALTURA INT
);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('AQP','RODRIGUEZ BALLON','AREQUIPA',2760);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('ATA','COMANDANTE FAP GERMAN ARIAS GRACIANI','HUARAZ',2977);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('AYP','CORONEL FAP ALFREDO MENDIVIL','AYACUCHO',2943);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('CJA','MAYOR GRAL. FAP ARMANDO REVOREDO','CAJAMARCA',2835);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('CUZ','ALEJANDRO VELAZCO ASTETE','CUZCO',3516);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('CIX','CAPITAN FAP JOSE QUIÑONES G.','CHICLAYO',31);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('IQT','CORONEL FAP FRANCISCO SECADA V.','IQUITOS',134);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('JUL','MANCO CAPAC','JULIACA',4140);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('LIM','INTERNACIONAL JORGE CHAVEZ','LIMA',25);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('PIU','CAPITAN FAP CARLOS CONCHA','PIURA',57);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('PEM','PADRE ALDAMIZ','PUERTO MALDONADO',281);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('TYL','CAPITAN FAP MONTES','TALARA',93);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('TRU','CAPITAN FAP CARLOS MARTINEZ PINILLOS','TRUJILLO',25);
INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES('TBP','CAPITAN FAP PEDRO CANGA','TUMBES',29);
DROP PROCEDURE IF EXISTS LISTAR_AEROPUERTOS;
DROP PROCEDURE IF EXISTS MOSTRAR_DATOS_AEROPUERTO;
DROP PROCEDURE IF EXISTS REGISTRAR_AEROPUERTO;
DELIMITER $
CREATE PROCEDURE LISTAR_AEROPUERTOS()
BEGIN
	SELECT CODIGO, NOMBRE FROM AEROPUERTO;
END$
CREATE PROCEDURE MOSTRAR_DATOS_AEROPUERTO(
	IN _CODIGO VARCHAR(10)
)
BEGIN
	SELECT ID_AEROPUERTO, CODIGO, NOMBRE, UBICACION, MTS_ALTURA FROM AEROPUERTO WHERE CODIGO = _CODIGO;
END$
CREATE PROCEDURE REGISTRAR_AEROPUERTO(
      IN _CODIGO VARCHAR(10), IN _NOMBRE VARCHAR(100), IN _UBICACION VARCHAR(50), IN _MTS_ALTURA INT(11)
)
BEGIN
      INSERT INTO AEROPUERTO(CODIGO, NOMBRE, UBICACION, MTS_ALTURA) VALUES (_CODIGO, _NOMBRE, _UBICACION, _MTS_ALTURA);
END$